#include "AsciiSPEReader.h"
#include "ByteUtils.h"
#include <algorithm>
#include <cmath>
#include <fstream>
#include <sstream>
namespace ust {
std::string AsciiSPEReader::name() const{return "Tagged ASCII SPE reader";}
bool AsciiSPEReader::supportsExtension(const std::string& e) const{return e==".spe";}
ReaderResult AsciiSPEReader::tryRead(const std::string& path,const std::vector<unsigned char>& raw) const{ ReaderResult r; r.readerName=name(); if(!mostlyText(raw)){r.reason="File is not predominantly text."; return r;} std::ifstream in(path); if(!in){r.reason="Text stream could not be opened."; return r;} std::vector<std::string> lines; std::string line; while(std::getline(in,line)) lines.push_back(line); std::size_t tag=lines.size(); for(std::size_t i=0;i<lines.size();++i){auto t=lower(trim(lines[i])); if(t=="$data:"||t=="$data"){tag=i;break;}} if(tag==lines.size()){r.reason="No $DATA section was found.";return r;} std::size_t rl=tag+1; while(rl<lines.size()&&trim(lines[rl]).empty()) ++rl; if(rl>=lines.size()){r.reason="$DATA section has no channel-range line.";return r;} long first=0,last=-1; {std::istringstream ss(lines[rl]); if(!(ss>>first>>last)||first<0||last<first){r.reason="Invalid channel range after $DATA.";return r;}} std::size_t expected=std::size_t(last-first+1); std::vector<double> counts; counts.reserve(expected); for(std::size_t i=rl+1;i<lines.size()&&counts.size()<expected;++i){auto t=trim(lines[i]); if(t.empty()) continue; if(t[0]=='$') break; std::istringstream ss(t); double v=0; while(ss>>v){counts.push_back(v); if(counts.size()==expected) break;}} if(counts.size()!=expected){std::ostringstream m; m<<"$DATA declares "<<expected<<" channels, but "<<counts.size()<<" values were read."; r.reason=m.str(); return r;} if(!std::all_of(counts.begin(),counts.end(),[](double x){return std::isfinite(x)&&x>=0;})){r.reason="$DATA contains invalid or negative counts.";return r;} r.matched=true;r.score=100;r.reason="Recognized $DATA-tagged ASCII SPE structure with a complete channel range."; r.data.counts=std::move(counts);r.data.rawBytes=raw;r.data.sourceFile=path;r.data.extension=extensionOf(path);r.data.detectedFormat="Tagged ASCII SPE";r.data.readerName=name();r.data.numericType="ASCII numeric text";r.data.byteOrder="not applicable";r.data.decisionReason=r.reason;r.data.fileSize=raw.size();r.data.channelCount=expected;r.data.readerScore=r.score;r.data.valid=true; return r;}
}
